CREATE TABLE request_body_tasks (
    id SERIAL PRIMARY KEY,
    task VARCHAR(255) NOT NULL,
    Accomplishment BOOLEAN DEFAULT FALSE
);
CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    email VARCHAR(64) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP DEFAULT NULL
);